# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b99da8d4551d028bbdef3ddc14b611e3053b5419aff88feb42ec65736b899a9800dcfd1cc607289302efc1d9eb1d49d621b5845bfc1f4b2abe0eb7783e36d4b

test:
  secret_key_base: 2120ab3a0e7f4e52efcb37dfa12f2a6495675581e7659f3bca7fcb0e03e21cde3b79c753a798e148d6d081b30c0bad50bb18a8443365686d62e6cb88bb818bf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
